#pragma once 

// Tap Hold
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// Combos
#define COMBO_TERM 20

// Caps Word
#define CAPS_WORD_INVERT_ON_SHIFT